name: tridentpro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  flutter_inappwebview: ^6.1.5
  sqflite: ^2.4.2
  icons_plus: ^5.0.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  pinput: ^5.0.1
  intl: ^0.19.0
  syncfusion_flutter_charts: ^29.1.41
  web_socket_channel: ^3.0.3
  image_picker: ^1.1.2
  lottie: ^3.3.1
  intl_phone_field: ^3.2.0
  path: ^1.9.1
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
